services:
  validator-app:
    build: ./backend
    command:
      - poetry
      - run
      - gunicorn
      - main:create_gunicorn_app
      - --worker-class
      - aiohttp.worker.GunicornWebWorker
      - -b
      - 0.0.0.0:8081
      - --reload
    depends_on:
      devbox:
        condition: service_healthy
    links:
      - devbox
    env_file:
      - ./env/app
      - .env
    tty: true
    volumes:
      - ./backend:/backend
  devbox:
    image: healthsamurai/aidboxone:edge
    depends_on:
      devbox-db:
        condition: service_healthy
    links:
      - 'devbox-db:database'
    ports:
      - '127.0.0.1:8080:8080'
    env_file:
      - ./env/aidbox
      - .env
    volumes:
      - ./resources:/resources
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      interval: 1s
      timeout: 20s
      retries: 100
      test: curl --fail http://devbox:8080/health || exit 1
  devbox-db:
    image: 'healthsamurai/aidboxdb:15.2'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
